version: '3'
services:
  db:
    image: postgres
    volumes:
      - 'pgdata:/var/lib/postgresql/data'
    ports:
      - '5432:5432'
  nuxt:
    build: ./front-end
    command: bash -c "yarn run dev"
    volumes:
      - './front-end:/nuxtapp'
    ports:
      - '3000:3000'
  rails:
    build: ./back-end
    command: tail -f /dev/null
    # command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 8080 -b '0.0.0.0'"
    volumes:
      - './back-end:/railsapp'
    ports:
      - '8080:8080'
      - "1234:1234"
      - "26166:26168"
    depends_on:
      - db
    environment:
      - DEVISE_JWT_SECRET_KEY=b"LyVC.N)#^MV??9qFXdWG=kC'?{/I
volumes:
  pgdata:
    external: true
